#!/bin/bash

# Author: Tairen Dunham
# Date: June 28, 2022
# Desc: Very simple cli tool using fzf to shortly navigate 
#       to my local git repos and checks status


suffix='/.git'

repo=$(locate -ber \\.git$ | 
grep '\/home\/turn\/Documents\/\|\/home\/turn\/.config\/' |
cut -d '/' -f5 |
dmenu -l 10)
  
repodir=$(locate -ber \\.git$ |
grep "$HOME\/Documents\/$repo\|$HOME\/.config\/$repo")

clear
cd "${repodir%$suffix}"
git status

read -p "view another? [y/n] : " next

case $next in
  [yY])
    exec list-repos
    ;;
    
  *   )
    cd "${repodir%$suffix}"
    ;;
esac
