#!/bin/sh
while true;
  do
    btc=$(btc)
    mem=$(memused) 
    blue=$(bluetooth)
    time=$(date '+%a %b %d | %H:%M ')
    bat=$(batterycap)

    xsetroot -name "$blue| BTC: \$$btc | $bat% | $mem | $time "

    sleep 5;
done;
