#! /bin/bash
while true;
  do
    btc=$(btc)
    mem=$(memused) 
    blue=$(bluetooth)
    time=$(date '+%a %b %d | %H:%M ')

    xsetroot -name "$blue| BTC: \$$btc | Used: $mem | $time "

    sleep 5;
done;
